### ISSUE TITLE
Would you mind to add LICENSE?

### ISSUE THREAD

**Issue by tani** [minoki/delimited-continuations-in-lua#1]
Hi, there. Thank you for the interesting snippets.
I am impressed to the implementation for reset-shift.
I would like to offer adding the OSS LICENSE for the code.
Would you mind to consider adding LICENSE such as MIT or GPL, UNLICENSE?

**Comment by minoki** [comment]
Added MIT License.

**Comment by tani** [comment]
Thank you so much!
